server:
  port: 9527
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: myzuul

zuul:
  prefix: /ssm
  ignored-services: "*"
  routes:
    user.serviceId: testnacos
    user.path: /user/**